import os
import io
import shutil
import subprocess
from typing import Optional
from fastapi import FastAPI, UploadFile, File, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from basic_pitch.inference import predict
from basic_pitch import ICASSP_2022_MODEL_PATH
from music21 import converter, key

app = FastAPI(title="ChoirAI Labs Production Pipeline")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SOLFA_MAP = {1: "do", 2: "re", 3: "mi", 4: "fa", 5: "sol", 6: "la", 7: "ti"}

@app.get("/")
def health_check():
    return {"status": "healthy", "pipeline": "Demucs + Basic Pitch + Music21 Active"}

@app.post("/transcribe")
async def transcribe_audio(
    file: UploadFile = File(...),
    manual_key: Optional[str] = Query(None, description="Optional override key like 'C', 'G', 'F#m', 'Am'")
):
    filename = str(file.filename)
    if not any(filename.lower().endswith(ext) for ext in [".wav", ".mp3", ".m4a", ".ogg", ".flac"]):
        raise HTTPException(status_code=400, detail="Unsupported audio file format.")

    # Define strict workspace folders
    temp_dir = "./choirai_pipeline_vault"
    demucs_out_dir = os.path.join(temp_dir, "separated")
    os.makedirs(temp_dir, exist_ok=True)
    
    input_audio_path = os.path.join(temp_dir, f"raw_{filename.replace(' ', '_')}")
    
    try:
        # 1. Save incoming audio stream to server storage
        with open(input_audio_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        # 2. RUN DEMUCS: Isolate the vocal/melody line from backing instrumentals
        # We use the 'htdemucs_light' model to optimize speed and RAM footprints on CPU
        try:
            subprocess.run([
                "demucs",
                "--two-stems=vocals",  # Separates track into 'vocals' vs 'other'
                "-n", "htdemucs_light",
                "-o", demucs_out_dir,
                input_audio_path
            ], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except Exception as demucs_err:
            raise Exception(f"Demucs source separation failed: {str(demucs_err)}")

        # Locate the clean isolated melody line generated by Demucs
        folder_name = os.path.splitext(os.path.basename(input_audio_path))[0]
        isolated_vocal_path = os.path.join(demucs_out_dir, "htdemucs_light", folder_name, "vocals.wav")
        
        if not os.path.exists(isolated_vocal_path):
            raise Exception("Pipeline failed to recover isolated melody track from separation layer.")

        # 3. RUN BASIC PITCH: Process the clean, isolated melodic wave track
        model_output, midi_data, note_events = predict(
            audio_path=isolated_vocal_path,
            model_or_model_path=ICASSP_2022_MODEL_PATH
        )
        
        midi_stream = io.BytesIO()
        midi_data.write(midi_stream)
        midi_stream.seek(0)
        
        # 4. RUN MUSIC21: Parse the absolute MIDI into a musicology framework
        score = converter.parse(midi_stream.read())
        
        # Lock down the tonal key
        if manual_key:
            try:
                detected_key = key.Key(manual_key)
            except Exception:
                raise HTTPException(status_code=400, detail=f"Invalid manual key override: {manual_key}")
        else:
            detected_key = score.analyze('key')
            
        target_scale = detected_key.getScale()
        raw_solfa_sequence = []
        
        # 5. Filter out noise anomalies and extract note structures
        for note_obj in score.flat.notes:
            # Ignore micro-ghost notes shorter than 0.18 seconds
            if note_obj.duration.quarterLength < 0.18:
                continue
                
            if hasattr(note_obj, 'pitch'):
                degree = target_scale.getScaleDegreeAndAccidental(note_obj.pitch)
                if isinstance(degree, tuple) and len(degree) > 0:
                    degree = degree[0]
                if degree in SOLFA_MAP:
                    raw_solfa_sequence.append(SOLFA_MAP[degree])
            elif hasattr(note_obj, 'pitches'):
                sorted_pitches = sorted(note_obj.pitches, key=lambda p: p.midi)
                if sorted_pitches:
                    degree = target_scale.getScaleDegreeAndAccidental(sorted_pitches[-1])
                    if isinstance(degree, tuple) and len(degree) > 0:
                        degree = degree[0]
                    if degree in SOLFA_MAP:
                        raw_solfa_sequence.append(SOLFA_MAP[degree])

        # Compress identical adjacent syllables for human sheet music readability
        clean_solfa = []
        for syllable in raw_solfa_sequence:
            if not clean_solfa or clean_solfa[-1] != syllable:
                clean_solfa.append(syllable)

        return {
            "success": True,
            "detected_key": f"{detected_key.tonic.name} {detected_key.mode.capitalize()}",
            "solfa": clean_solfa,
            "note_count": len(clean_solfa)
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Pipeline Error: {str(e)}")
        
    finally:
        # Always purge workspace processing cache paths to save disk space
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)
